Upgrade to PHP 7.1+
php-fig/log pull request #64
Opened 2019-08-03 16:39 UTC by codemasher

Hi, i'd like to see the common psr interfaces upgraded to PHP 7! Can we please have this in near future?

2019-08-05 09:28 UTC, Jean85 commented
We've already said that this is not doable to the current PSR. We started a conversation about making PSRs evolve in this regard on our ML: https://groups.google.com/d/topic/php-fig/OyC3plRYhqg/discussion

2020-08-19 23:01 UTC, tdtm commented
Considering this was approved: https://github.com/php-fig/fig-standards/pull/1195, could this be merged into a 2.0.0?

2020-08-20 05:05 UTC, arnested commented
But that doesn't match [the specification](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-3-logger-interface.md)?
> Every method accepts a string as the message, or an object with a __toString() method. Implementors MAY have special handling for the passed objects. If that is not the case, implementors MUST cast it to a string.

2020-08-20 17:54 UTC, stof commented
indeed, typehint `string` does not match the specification, as the actual type is `string|Stringable`

2020-08-21 07:03 UTC, Jean85 commented
> the actual type is `string|Stringable`

That would be attainable with PHP 8 though...

2020-08-21 08:37 UTC, stof commented
@Jean85 I think making PHP 8 the min supported version is too early...

2021-04-25 09:20 UTC, GrahamCampbell requested changes

2021-04-25 09:20 UTC, GrahamCampbell commented on .gitignore
> +.idea
👎 This belongs in your global ignore file.

2021-07-14 15:20 UTC, Crell commented
Closing in favor of #76 and #77, which were just approved.

2021-07-14 15:20 UTC, closed without merging