Clarify type of 2nd argument `context`
php-fig/log pull request #74
Opened 2021-05-02 10:02 UTC by Jeckerson

According to psalm, there is an error:

> ERROR: MethodSignatureMismatch - ide/5.0.0-alpha.1/Phalcon/DataMapper/Pdo/Profiler/MemoryLogger.zep.php:21:7 - Argument 2 of Psr\Log\AbstractLogger::alert has wrong type 'mixed', expecting 'array<array-key, mixed>' as defined by Psr\Log\LoggerInterface::alert (see https://psalm.dev/042)

This blocks https://github.com/phalcon/cphalcon/pull/15362

2021-05-03 08:06 UTC, Jean85 requested changes
Sorry but I'm :-1: on this change: you're making the type more generic without any reason.

2021-05-03 08:16 UTC, Jeckerson commented
Then implementation must be compliant with this "not generic" type.

https://github.com/php-fig/log/blob/a18c1e692e02b84abbafe4856c3cd7cc6903908c/Psr/Log/AbstractLogger.php#L18

2021-05-03 08:20 UTC, Jean85 commented
The issue is in the `AbstractLogger` then. By spec, the `$context` is an array of mixed, unspecified data: https://www.php-fig.org/psr/psr-3/

So `mixed[]` is correct.

2021-05-03 08:33 UTC, Jean85 approved these changes

2021-05-03 11:20 UTC, merged

2021-05-03 11:20 UTC, Seldaek commented
Thanks, looks good to me like this.

2022-10-09 10:57 UTC, Sebastianoskiojoj commented
{{ dict 
	"country" "Norway" 
	"population" "5 millions"
	"language" "Norwegian"
	"language_code" "nb"
	"weather" "freezing cold"
	"capitol" "Oslo"
	"largest_city" "Oslo"
	"currency"  "Norwegian krone"
	"dialing_code" "+47" 
}}

2022-10-09 10:58 UTC, Sebastianoskiojoj commented
Psr/Log/AbstractLogger.php