Narrow supported log level phpdoc
php-fig/log pull request #79
Opened 2023-11-28 08:08 UTC by mvorisek

Only the `LogLevel::*` log levels need to be supported per https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-3-logger-interface.md#11-basics

User can still widen the accepted type like `LogLevel::*|'xxx'` thanks to LSP.

2023-11-28 09:10 UTC, Seldaek approved these changes
I guess this makes sense yes.

2023-12-13 21:34 UTC, mvorisek commented
Can it be merged and released?

2023-12-14 08:47 UTC, Jean85 commented
This may require a change in the spec..

2023-12-14 11:08 UTC, mvorisek commented
> This may require a change in the spec..

@Jean85 please see the linked spec in the PR description, citing:

> A ninth method, log, accepts a log level as the first argument. Calling this method with one of the log level constants MUST have the same result as calling the level-specific method. Calling this method with a level not defined by this specification MUST throw a Psr\Log\InvalidArgumentException if the implementation does not know about the level. Users SHOULD NOT use a custom level without knowing for sure the current implementation supports it.

So I belive the spec. allows this change, as the phpdoc in this PR is basically equivalent to the "Calling this method with a level not defined by this specification MUST throw".

2024-05-03 12:02 UTC, mvorisek commented
I belive I have prooven what needs to be proven, can this PR be merged, please 🙏?

2024-05-03 15:37 UTC, KorvinSzanto commented
This is a breaking change and disallows the valid use case of a implementor adding a custom log level: https://www.php-fig.org/psr/psr-3/#11-basics

This could only merge if arbitrary strings are still allowed.

2024-05-03 18:22 UTC, KorvinSzanto requested changes
See my comment. To demonstrate my concern, compare these:

- Current `mixed` type: https://psalm.dev/r/b15a7f5725
- PR proposed type: https://psalm.dev/r/8e53dc846d
- My recommendation: https://psalm.dev/r/e4306f884a

2024-05-03 20:04 UTC, mvorisek commented
@KorvinSzanto please see https://github.com/php-fig/log/pull/79#issuecomment-1855646852 - the spec already defines:

> Users SHOULD NOT use a custom level without knowing for sure the current implementation supports it.

that the default interface does not support any other log level by default.

Thank to LSP, user can widen the accepted type:

- https://phpstan.org/r/874bb24d-4daa-479c-80ba-08f5ebb07e65
- https://psalm.dev/r/3c98113bc9

working in both/all static analysers.

Given this, I belive this PR is not violating the spec.

2024-05-03 20:05 UTC, mvorisek commented
@KorvinSzanto please see https://github.com/php-fig/log/pull/79#issuecomment-1855646852 - the spec already defines:

> Users SHOULD NOT use a custom level without knowing for sure the current implementation supports it.

that the default interface does not support any other log level by default.

Thank to LSP, user can widen the accepted type:

- https://phpstan.org/r/874bb24d-4daa-479c-80ba-08f5ebb07e65
- https://psalm.dev/r/3c98113bc9

working in both/all static analysers.

Given these facts, I belive this PR is not violating the spec.

2024-05-03 21:14 UTC, KorvinSzanto commented
> @KorvinSzanto please see [#79 (comment)](https://github.com/php-fig/log/pull/79#issuecomment-1855646852) - the spec already defines:
> 
> > Users SHOULD NOT use a custom level without knowing for sure the current implementation supports it.
> 
> that the default interface does not support any other log level by default.

`SHOULD NOT` means that something is allowed but discouraged https://datatracker.ietf.org/doc/html/rfc2119#section-4 :

> [4](https://datatracker.ietf.org/doc/html/rfc2119#section-4). SHOULD NOT   This phrase, or the phrase "NOT RECOMMENDED" mean that
   there may exist valid reasons in particular circumstances when the
   particular behavior is acceptable or even useful, but the full
   implications should be understood and the case carefully weighed
   before implementing any behavior described with this label.

And so for the purposes of this discussion, in my opinion, the quote you show is effectively the same as "Users MAY use a custom level without knowing ..." and by changing the type here to disallow that use case we're going from `SHOULD NOT` (or `MAY`) to `MUST NOT` since you must know and use a subtype for this functionality to work.

> Thank to LSP, user can widen the accepted type:
> 
> * https://phpstan.org/r/874bb24d-4daa-479c-80ba-08f5ebb07e65
> * https://psalm.dev/r/3c98113bc9
> 
> working in both/all static analysers.

That's not an argument for narrowing the type in this case. Most implementors simply inherit the type from the parent, for example symfony: 
https://github.com/symfony/symfony/blob/7.0/src/Symfony/Component/HttpKernel/Log/Logger.php#L93 and so what you are advocating for is implementors _change their code_ to maintain compatibility with the current API which is, to me, a breaking change.

> Given these facts, I belive this PR is not violating the spec.

I disagree. Can you take a second and speak to the value of narrowing this type rather than just using an intersection or union type with `mixed`?

2024-09-11 13:20 UTC, Seldaek commented
Closing as I don't think this is worth the risk of breaking something, and having mixed|LogLevel::* is kinda just mixed.. so I don't think it'd fix anything IDEs?

In any case, the log method is bad IMO, especially if you want completion, use ->warning etc.

2024-09-11 13:20 UTC, closed without merging